# go-http

###
# @name Send NotAllowed Method
GET http://localhost:8080/api/v1/fetch

###
# @name Fetch correct URL list
POST http://localhost:8080/api/v1/fetch
Content-Type: application/json

[
  "https://go.dev/images/go-logo-white.svg"
]

###
# @name Fetch huge URL list
POST http://localhost:8080/api/v1/fetch
Content-Type: application/json

[
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg",
  "https://go.dev/images/go-logo-white.svg"
]

###
# @name Fetch empty URL list
POST http://localhost:8080/api/v1/fetch
Content-Type: application/json

[]

###
# @name Fetch nil list
POST http://localhost:8080/api/v1/fetch

###
# @name Fetch URL list with URL access time deadline exceeded
POST http://localhost:8080/api/v1/fetch
Content-Type: application/json

[
  "http://images.cocodataset.org/zips/train2014.zip",
  "https://go.dev/images/go-logo-white.svg"
]