name: gochecks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  gochecks:
    strategy:
      matrix:
        go: ['1.21']
        os: [macos-latest, ubuntu-latest]

    name: checks
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: go build
        run: go build -o go-http cmd/main.go
      - name: go test
        run: go test -race ./.../handler
      - name: go vet
        run: go vet ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          args: --timeout 3m --verbose
          version: v1.54
      - name: staticccheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
          version: latest
          cache-key: ${{ matrix.go }}